FoodFinder/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from FoodFinder import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main_app/', include("main_app.urls")),
    path('user/', include("users.urls")),
    url(r'^$', views.Mainview.as_view(), name='main'),
    url(r'about/', views.Aboutview.as_view(), name='about'),
    path('exercise/', include('exercise.urls')),
    path('maps/', include('maps.urls')),
    path('foodlist/', include('foodboard.urls')),
    path('imagecla/', include('imagecla.urls')),
    path('photo/', include('photo.urls')),
    path('check/', include('check.urls')),
    path('suggestfood/', include('suggestfood.urls'))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maps/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url

import maps.views
from FoodFinder import views

urlpatterns = [
    path('', maps.views.index, name='index'),
]

suggestfood/urls.py
from django.urls import path
from . import views

app_name ='suggestfood'
urlpatterns = [
    path('suggestfood/',views.export, name="suggestfood"),
    path('suggest/',views.recomomandlist, name='suggest')
]

templates/suggest/create.html
{% extends 'index.html' %}
{% block contents %}
<body>
<center>
    <h3>회원님께 제공드리는 추천음식 목록</h3>
<br><a href="{% url 'suggestfood:suggest' %}">목록으로</a>
    <br><p>목록에서 확인하실 수 있습니다!</p>
</center>

</body>
<br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock contents%}

templates/suggest/suggestlist.html
{% extends 'index.html' %}
{% block contents %}
<body>
<center>
<h3>회원님에게 추천드리는 음식</h3>
 <p>1등 : {{suggest.1}}</p>
<p>2등 : {{suggest.2}}</p>
<p>3등 : {{suggest.3}}</p>
</center>
</body>
</center>
{% endblock%}