FoodFinder/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from FoodFinder import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main_app/', include("main_app.urls")),
    path('user/', include("users.urls")),
    url(r'^$', views.Mainview.as_view(), name='main'),
    url(r'about/', views.Aboutview.as_view(), name='about'),
    path('exercise/', include('exercise.urls')),
    path('maps/', include('maps.urls')),
    path('foodlist/', include('foodboard.urls')),
    path('imagecla/', include('imagecla.urls')),
    path('photo/', include('photo.urls')),
    path('check/', include('check.urls')),
    path('suggestfood/', include('suggestfood.urls'))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodboard/urls.py
from django.conf.urls import url
from foodboard import views
app_name = 'foodboard'

urlpatterns = [
        url(r'^$', views.FoodList.as_view(), name='food_list'),
        url(r'^detail/(?P<pk>\d+)$', views.fooddetail.as_view(), name='foodboard_detail'),
        url('result/', views.searchresult, name='results')
    ]

imagecla/urls.py
from django.urls import path
from imagecla import views

app_name ='imagecla'

urlpatterns = [
    path('analimg/', views.Deeplearn),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('image/',views.handle_uploaded_file, name='image')
]

maps/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url

import maps.views
from FoodFinder import views

urlpatterns = [
    path('', maps.views.index, name='index'),
]

photo/urls.py
from django.urls import path
from .views import PhotoList, PhotoDelete, PhotoDetail, PhotoUpdate, PhotoCreate, PhotoLike, PhotoFavorite, \
    PhotoLikeList, PhotoFavoriteList, PhotoMyList

app_name = "photo"
urlpatterns = [
    path("mylist/", PhotoMyList.as_view(), name='mylist'),
    path("create/", PhotoCreate.as_view(), name='create'),
    path("like/<int:photo_id>/", PhotoLike.as_view(), name='like'),
    path("favorite/<int:photo_id>/", PhotoFavorite.as_view(), name='favorite'),
    path("delete/<int:pk>/", PhotoDelete.as_view(), name='delete'),
    path("update/<int:pk>/", PhotoUpdate.as_view(), name='update'),
    path("detail/<int:pk>/", PhotoDetail.as_view(), name='detail'),
    path("like/", PhotoLikeList.as_view(), name="like_list"),
    path("favorite/", PhotoFavoriteList.as_view(), name="favorite_list"),
    path("", PhotoList.as_view(), name='index'),
]

from django.conf.urls.static import static

from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

suggestfood/urls.py
from django.urls import path
from . import views

app_name ='suggestfood'
urlpatterns = [
    path('suggestfood/',views.export, name="suggestfood"),
    path('suggest/',views.recomomandlist, name='suggest')
]

templates/create.html
{% extends 'index.html' %}
{% block contents %}
<body>
<center> 추천사이트를 만들거에요!</center>

</body>
{% endblock contents%}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html style="font-size: 16px;">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="Ways to manage sugar, Lower sugar recipes, New ideas to life, Health is the most precious">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>Home</title>
    <link rel="stylesheet" href='{% static "nicepage.css" %}' media="screen">
      <link rel="stylesheet" href='{% static "about.css" %}' media="screen">
      <link rel="stylesheet" href='{% static "foodboard.css" %}' media="screen">
      <link rel="stylesheet" href='{% static "foodboardDetail.css" %}' media="screen">
      <link rel="stylesheet" href='{% static "Exercise.css" %}' media="screen">
      <link rel="stylesheet" href='{% static "ExerciseDetail.css" %}' media="screen">
      <link rel="stylesheet" href='{% static "Pic" %}' media="screen">
      <link rel="stylesheet" href='{% static "picresult.css" %}' media="screen">
      <link rel="stylesheet" href='{% static "result1.css" %}' media="screen">

    <script class="u-script" type="text/javascript" src='{% static "jquery.js" %}' defer=""></script>
    <script class="u-script" type="text/javascript" src='{% static "nicepage.js" %}' defer=""></script>
    <meta name="generator" content="Nicepage 3.11.0, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald:200,300,400,500,600,700">
    
    
    
    
    
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "",
		"url": "index.html",
		"logo": "#"
}</script>
    <meta property="og:title" content="Home">
    <meta property="og:type" content="website">
    <meta name="theme-color" content="#a68053">
    <link rel="canonical" href="index.html">
    <meta property="og:url" content="index.html">
  </head>
  <body data-home-page="Home.html" data-home-page-title="Home" class="u-body u-overlap">
  <header class="u-clearfix u-header u-header" id="sec-46b8"><div class="u-clearfix u-sheet u-sheet-1">
      <br>
        <nav class="u-align-left u-menu u-menu-dropdown u-nav-spacing-25 u-offcanvas u-menu-1" data-responsive-from="XL">
          <div class="menu-collapse">
            <a class="u-button-style u-nav-link u-text-black" href="#" style="font-size: calc(1em + 20px); padding: 10px 18px;">
              <svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 302 302" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-7b92"></use></svg>
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="svg-7b92" x="0px" y="0px" viewBox="0 0 302 302" style="enable-background:new 0 0 302 302;" xml:space="preserve" class="u-svg-content"><g><rect y="36" width="302" height="30"></rect><rect y="236" width="302" height="30"></rect><rect y="136" width="302" height="30"></rect>
</g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g></svg>
            </a>
          </div>
          <div class="u-custom-menu u-nav-container-collapse">
            <div class="u-align-center u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
              <div class="u-sidenav-overflow">
                <div class="u-menu-close"></div>
                <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="/" style="padding: 8px 0px;">Home</a>
    </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="/about" style="padding: 8px 0px;">About</a>
    </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'profile' %}" style="padding: 8px 0px;">MyPage</a>
    </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'foodboard:food_list' %}" style="padding: 8px 0px;">Foodboard</a>
    </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="/maps" style="padding: 8px 0px;">Maps</a>
    </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="/exercise" style="padding: 8px 0px;">Exercise</a>
    </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'imagecla:upload_file' %}" style="padding: 8px 0px;">Pic</a>
                    </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'photo:index' %}" style="padding: 8px 0px;">Community</a>
                   </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="/check" style="padding: 8px 0px;">Calculator</a>
                    </li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="{% url 'suggestfood:suggestfood' %}" style="padding: 8px 0px;">Recommend</a>
    </li></ul>
              </div>
            </div>
            <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
          </div>
        </nav>
      </div>  {% block contents %}</header>





  {% endblock contents %}
    <footer class="u-clearfix u-footer u-grey-80" id="sec-d5fe"><div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-align-center u-container-style u-group u-group-1">
          <div class="u-container-layout u-valign-middle u-container-layout-1">
            <p class="u-small-text u-text u-text-1">© Fooodfinder Corp.</p>
          </div>
        </div>
      </div></footer>
  </body>
</html>

templates/photobase.html
{% extends 'index.html' %}
{% block contents %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
 {% load static %}
    <style>
    .btn-like{
        display: inline-block;
        width: 50px;
        height: 50px;
        background:url({% static 'images/instagramicon.png' %});
        background-position: -100px -400px;
        text-indent: -9999px;
        overflow:hidden;
        border:none;
    }
    .btn-like.active{
    display: inline-block;
        width: 50px;
        height: 50px;
        background:url({% static 'images/instagramicon.png' %});
        background-position: -50px -400px;
        text-indent: -9999px;
        overflow:hidden;
        border:none;
    }
     .btn-favorite{
        display: inline-block;
        width: 50px;
        height: 50px;
        background:url({% static 'images/instagramicon.png' %});
        background-position: -515px -150px;
        text-indent: -9999px;
        overflow:hidden;
        border:none;
    }
    .btn-favorite.active{
    display: inline-block;
        width: 50px;
        height: 50px;
        background:url({% static 'images/instagramicon.png' %});
        background-position: -515px -100px;
        text-indent: -9999px;
        overflow:hidden;
        border:none;
    }

    </style>



    <div align="center">
        <ul>
            <button class="btn btn-secondary" onclick="location.href='{% url 'photo:index' %}'">
                main
            </button>
            {% if user.is_authenticated %}
            <button class="btn btn-secondary" onclick="location.href='{% url 'photo:create' %}'">
                사진올리기
            </button>
            <button class="btn btn-secondary" onclick="location.href='{% url 'photo:like_list' %}'">
                좋아요한 사진보기
            </button>
            <button class="btn btn-secondary" onclick="location.href='{% url 'photo:favorite_list' %}'">
                저장한 사진보기
            </button>
            {% else %}
            <button class="btn btn-secondary" onclick="location.href='{% url 'login' %}'">Login
            </button>
            {% endif %}
        </ul>
    </div>
<div class='container'>
    {% if messages %}
    <div class="row">
        <div class="col"></div>
        <div class="col-6">
            {% for message in messages %}
            <div class="alert alert-{{message.tag}}">{{message}}</div>
            {% endfor %}
        </div>
        <div class="col"></div>
    </div>
</div>
    {% endif %}

{% block content %}
{% endblock %}




<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>
{% endblock contents %}