FoodFinder/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from FoodFinder import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main_app/', include("main_app.urls")),
    path('user/', include("users.urls")),
    url(r'^$', views.Mainview.as_view(), name='main'),
    url(r'about/', views.Aboutview.as_view(), name='about'),
    path('exercise/', include('exercise.urls')),
    path('maps/', include('maps.urls')),
    path('foodlist/', include('foodboard.urls')),
    path('imagecla/', include('imagecla.urls')),
    path('photo/', include('photo.urls')),
    path('check/', include('check.urls')),
    path('suggestfood/', include('suggestfood.urls'))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodboard/urls.py
from django.conf.urls import url
from foodboard import views
app_name = 'foodboard'

urlpatterns = [
        url(r'^$', views.FoodList.as_view(), name='food_list'),
        url(r'^detail/(?P<pk>\d+)$', views.fooddetail.as_view(), name='foodboard_detail'),
        url('result/', views.searchresult, name='results')
    ]

maps/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url

import maps.views
from FoodFinder import views

urlpatterns = [
    path('', maps.views.index, name='index'),
]

foodboard/models.py
from django.db import models

class Foodclass(models.Model):
    name = models.CharField('식품명', max_length=50, unique=False)
    once = models.FloatField('1회 제공량', default=0)
    calories = models.FloatField('칼로리', default=0)
    cabor = models.FloatField('탄수화물', default=0)
    protein = models.FloatField('단백질', default=0)
    fat = models.FloatField('지방', default=0)
    def __str__(self):
        return self.name

foodboard/forms.py
from django import forms
class Postsearch(forms.Form):
    search = forms.CharField(label='Search')

foodboard/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.views.generic import DetailView, ListView, FormView
from django.contrib import messages
from django.db.models import Q

from .forms import Postsearch
from .models import Foodclass
# Create your views here.
class FoodList(ListView):
    model = Foodclass
    paginate_by = 30
    template_name = 'FoodBoard.html'

class fooddetail(DetailView):
    model = Foodclass
    template_name = 'foodboardDetail.html'
    context_object_name = 'board'

def searchresult(request):
    query = request.GET['query']
    if query:
        posts = Foodclass.objects.filter(name__contains=query)
    return render(request, 'searchresult.html',{'posts':posts})

foodboard/templates/foodboardDetail.html
{% extends 'index.html' %}
<!DOCTYPE html>
{% load static %}
<html style="font-size: 16px;">
{% block contents %}
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="Design Online">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>foodboardDetail</title>

  </head>
    <section class="u-align-center u-clearfix u-section-1" id="sec-65a2">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <div class="u-container-style u-group u-group-1">
          <div class="u-container-layout u-valign-middle u-container-layout-1">
            <h2 class="u-align-center u-text u-text-2" data-animation-name="zoomIn" data-animation-duration="1000" data-animation-delay="0" data-animation-direction="Down">{{ board.name }}</h2>
            <br>
            <br>
            <table class="u-table-entity u-table-entity-1">
              <tr style="height: 65px;">
                <td class="u-table-cell">1회 제공량</td>
                <td class="u-table-cell">칼로리</td>
                <td class="u-table-cell">탄수화물</td>
                <td class="u-table-cell">단백질</td>
                <td class="u-table-cell">지방</td>
              </tr>
                <tr style="height: 65px;">
                <td class="u-table-cell">{{ board.once }}g</td>
                <td class="u-table-cell">{{ board.calories }}kcal</td>
                <td class="u-table-cell">{{ board.cabor }}</td>
                <td class="u-table-cell">{{ board.protein }}</td>
                <td class="u-table-cell">{{ board.fat }}</td>
              </tr>

              <div>
                <a href="{% url 'foodboard:food_list' %}">식품 목록으로</a>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4"></script>
<center>
<canvas id="chart" width="500" height="400"></canvas>
<script>

      let ctx = document.getElementById("chart").getContext("2d");
      let chart = new Chart(ctx, {
          type: "bar",
          data: {
             labels: ["1회 제공량","칼로리", "탄수화물(g)", "단백질(g)", "지방(g)"],
             datasets: [
                {
                  label: "함유량 (g)",
                  backgroundColor: "#79AEC8",
                  borderColor: "#417690",
                  data:[{{ board.once }}, {{ board.calories }}, {{ board.cabor }} ,{{ board.protein }}, {{ board.fat }} ]
                }
             ]
          },
          options: {
            responsive :false,
             title: {
                text: "{{ board.name }} 그래프",
                display: true
             }
          }
          });


  </script>

</center>
              </div>
          </table>
          </div>
          </div>
        </div>
      </div>

    </section>

  </body>
{% endblock contents %}
</html>

foodboard/templates/searchresult.html
{% extends 'index.html' %}
{% load static %}
<html style="font-size: 16px;">
{% block contents %}
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>result</title>

  </head>
<body>
  <center><h3>검색결과</h3></center></header>
<br><br><br><br><br><br>
    <section class="u-align-center u-clearfix u-white u-section-1" id="carousel_0766" >
          <center><a href="{% url 'foodboard:food_list' %}">뒤로가기</a></center>
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
            <div class="u-container-layout u-similar-container u-container-layout-1" align="left">
                        {% for post in posts %}
                <p>이름 : <a href="{% url 'foodboard:foodboard_detail' post.id %}">{{ post.name }}</a></p>
                {% empty %}
                    no results.
        {% endfor %}
        </div>
      </div>
    </section>

  </body>
{% endblock contents %}
</html>